export const SCHEDULE_DATA = [
  { id: 1, day: "שבת", planned: "12:00", lap: "1", food: "3 תמרים + בייגלה", drink: "בקבוק איזוטון", supps: "", gear: "קרם הגנה", clothing: "קצר 1", notes: "" },
  { id: 2, day: "שבת", planned: "13:00", lap: "1", food: "חצי פיתה + חמ.בוטנים", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 3, day: "שבת", planned: "14:00", lap: "1+2", food: "3 תמרים + בייגלה", drink: "בקבוק איזוטון", supps: "", gear: "", clothing: "", notes: "" },
  { id: 4, day: "שבת", planned: "15:00", lap: "2", food: 'חצי פיתה גבנ"צ', drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 5, day: "שבת", planned: "16:00", lap: "2", food: "3 תמרים + בייגלה", drink: "בקבוק איזוטון", supps: "חטיף חלבון + אספרסו + כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 6, day: "שבת", planned: "17:00", lap: "3", food: "חצי פיתה חמ.בוטנים+ריבה + מנה חמה", drink: "קולה", supps: "", gear: "", clothing: "", notes: "" },
  { id: 7, day: "שבת", planned: "18:00", lap: "3", food: 'חצי פיתה גבנ"צ + חצי חטיף חלבון', drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 8, day: "שבת", planned: "19:00", lap: "3+4", food: "חטיף", drink: "בקבוק איזוטון", supps: "אספרסו", gear: "פנס ראש", clothing: "", notes: "" },
  { id: 9, day: "שבת", planned: "20:00", lap: "4", food: "חצי פיתה חמ.בוטנים", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 10, day: "שבת", planned: "21:00", lap: "4", food: "חטיף + חצי חטיף חלבון", drink: "מים", supps: "", gear: "", clothing: "", notes: "שקיעה 21:21 🌅" },
  { id: 11, day: "שבת", planned: "22:00", lap: "5", food: "חטיף ספונסר + ג'ל + מנה חמה", drink: "קולה", supps: "אספרסו", gear: "", clothing: "חליפה חמה", notes: "" },
  { id: 12, day: "שבת", planned: "23:00", lap: "5", food: "חטיף", drink: "בקבוק איזוטון", supps: "כדור מלח + אספרסו", gear: "", clothing: "", notes: "" },
  { id: 13, day: "ראשון", planned: "00:00", lap: "5+6", food: "עוגה", drink: "בקבוק איזוטון", supps: "", gear: "", clothing: "", notes: "" },
  { id: 14, day: "ראשון", planned: "01:00", lap: "6", food: "פיתה חמ.בוטנים + חצי חטיף חלבון", drink: "מים", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 15, day: "ראשון", planned: "02:00", lap: "6", food: "חטיף + חטיף חלבון", drink: "בקבוק איזוטון", supps: "אספרסו", gear: "", clothing: "", notes: "" },
  { id: 16, day: "ראשון", planned: "03:00", lap: "7", food: "חטיף SPONSER", drink: "קולה", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 17, day: "ראשון", planned: "04:00", lap: "7", food: "עוגה SIS", drink: "מים", supps: "MUSCLE RELAX", gear: "", clothing: "נעליים", notes: "זריחה 04:41 🌄" },
  { id: 18, day: "ראשון", planned: "05:00", lap: "7+8", food: "חטיף SPONSER + חטיף חלבון", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 19, day: "ראשון", planned: "06:00", lap: "8", food: 'חצי פיתה גבנ"צ + חצי חטיף חלבון', drink: "מים", supps: "אספרסו", gear: "קרם הגנה", clothing: "קצר 2", notes: "" },
  { id: 20, day: "ראשון", planned: "07:00", lap: "8", food: "עוגה SIS + ג'ל", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 21, day: "ראשון", planned: "08:00", lap: "9", food: "חטיף SPONSER + חטיף חלבון", drink: "קולה", supps: "", gear: "", clothing: "", notes: "" },
  { id: 22, day: "ראשון", planned: "09:00", lap: "9", food: "חטיף קליף", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 23, day: "ראשון", planned: "10:00", lap: "9+10", food: "2 ופל GU", drink: "מים", supps: "MUSCLE RELAX", gear: "", clothing: "", notes: "" },
  { id: 24, day: "ראשון", planned: "11:00", lap: "10", food: "מנה חמה פירה + חטיף ספונסר", drink: "בקבוק איזוטון", supps: "כדור מלח", gear: "", clothing: "", notes: "" },
  { id: 25, day: "ראשון", planned: "12:00", lap: "10", food: "סיום 🏆", drink: "—", supps: "—", gear: "—", clothing: "—", notes: "סיום מרוץ!" },
];

export const GEAR_DATA = [
  { id: 1, cat: "הלבשה", name: "נעלי שטח עמידות לבוץ/מים", desc: "ניקוז מים ונידוף זיעה", mandatory: true },
  { id: 2, cat: "הלבשה", name: "גרביים סינתטיים", desc: "ייבוש מהיר, ללא כותנה", mandatory: true },
  { id: 3, cat: "הלבשה", name: "סט בגדים יבש", desc: "טייץ, חולצה, ג'קט", mandatory: true },
  { id: 4, cat: "חימום", name: "שכבת בסיס תרמית", desc: "לשמירה על חום הגוף", mandatory: true },
  { id: 5, cat: "חימום", name: "כובע חם/בנדנה", desc: "לשעות הקרות/לילה", mandatory: false },
  { id: 6, cat: "הגנה", name: "כפפות ניאופרן", desc: "למגע עם מים/קרח", mandatory: false },
  { id: 7, cat: "תאורה", name: "פנס ראש + סוללות", desc: "חובה בלילה", mandatory: true },
  { id: 8, cat: "זהות", name: "גופיית צוות / ביגוד אחיד", desc: "לזיהוי קבוצתי", mandatory: false },
  { id: 9, cat: "הלבשה", name: "שעון ספורט", desc: "מעקב קצב וזמן", mandatory: true },
  { id: 10, cat: "אחסון", name: "תיק גב קטן", desc: "לציוד אישי", mandatory: true },
  { id: 11, cat: "ניקוי", name: "מגבת מיקרופייבר", desc: "קומפקטית, מתייבשת מהר", mandatory: true },
  { id: 12, cat: "בריאות", name: "קרם נגד שפשפות", desc: "ואזלין/Anti-chafe", mandatory: true },
  { id: 13, cat: "חירום", name: "פלסטרים + סלוטייפ + בנגיי", desc: "לעזרה עצמית וציוד", mandatory: true },
  { id: 14, cat: "תזונה", name: "ג'לים אנרגטיים", desc: "לאנרגיה מיידית", mandatory: true },
  { id: 15, cat: "תזונה", name: "חטיפי חלבון / תמרים", desc: "נשנוש מהיר", mandatory: true },
  { id: 16, cat: "מים", name: "בקבוק מים אישי", desc: '500–750 מ"ל', mandatory: true },
  { id: 17, cat: "בריאות", name: "תרופות + תוספים (מגנזיום/אדוויל/מלח)", desc: "תרופות קבועות", mandatory: true },
  { id: 18, cat: "חשמל", name: "מטען נייד (Power Bank)", desc: "לטעינת פנסים וטלפונים", mandatory: true },
  { id: 19, cat: "הגנה", name: "נרתיק אטום למים", desc: "למזומן, טלפון, מזהים", mandatory: true },
  { id: 20, cat: "הלבשה", name: "מעיל פוך/חרמונית", desc: "", mandatory: false },
  { id: 21, cat: "כללי", name: "שקיות אטומות לבדים רטובים", desc: "הגנה מרטיבות", mandatory: true },
  { id: 22, cat: "שתייה חמה", name: "תרמוסים", desc: "להכנת מרקים ותה", mandatory: true },
];

export const LOGISTICS_DATA = [
  { name: "רכב שכור", desc: "לבדוק + לצלם", mandatory: true },
  { name: "אוהל גדול ל-8", desc: "עם קירות צד, הגנה מגשם", mandatory: true },
  { name: "גזיבו/שמשייה", desc: "אזור ישיבה חיצוני", mandatory: false },
  { name: "שולחן מתקפל", desc: "לארוחות ותחנות ביניים", mandatory: true },
  { name: "כיסאות קמפינג", desc: "צוות לוגיסטי", mandatory: false },
  { name: "צידנית + מים", desc: "10 ליטר + שתייה איזוטונית", mandatory: true },
  { name: "תחנת עזרה ראשונה", desc: "גזות, פלסטרים, יוד, מד חום", mandatory: true },
  { name: "גזייה + קומקום חשמלי", desc: "אבי וקובי מביאים", mandatory: true },
  { name: "פנסים + תאורה", desc: "פנס תליה + סולאריים", mandatory: true },
  { name: "מאריך חשמל", desc: "לטעינת פנסים וטלפונים", mandatory: true },
  { name: "חבל לתליה", desc: "לייבוש בגדים", mandatory: false },
  { name: "שקיות אשפה גדולות", desc: "מהארץ × 10", mandatory: true },
  { name: "ערכת תיקון חירום", desc: "חבל, דבק, אזיקונים, טוש", mandatory: true },
  { name: "לדרמן × 2", desc: "כמות 2", mandatory: true },
];

export const ADMIN_PIN = "2626";

export const ENVIRONMENT_TRIGGERS = [
  { id: "sunset", time: "19:30", title: "☀️ שקיעה מתקרבת", text: "חובה להכין: פנס ראש + סוללות גיבוי ומעיל רוח." },
  { id: "dinner", time: "21:00", title: "🍲 ארוחת ערב", text: "זמן למנה חמה מרוכזת / פירה חם בפיטס." },
  { id: "midnight", time: "00:00", title: "🌙 חצות הליל", text: "הטמפרטורה צונחת. לבדוק אם צריך להחליף לביגוד תרמי ארוך." },
  { id: "sunrise", time: "05:30", title: "🌅 זריחה", text: "להכין: משקפי שמש, לרענן קרם הגנה, ולהוריד פנסי ראש." },
];
